<?php

namespace App\Controller\Admin;

use App\Entity\LieuStockage;
use App\Entity\OperationStock;
use App\Entity\Parametre;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Config\UserMenu;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;


class DashboardController extends AbstractDashboardController
{
    /**
     * @Route("/admin", name="admin")
     */
    public function index(): Response
    {
        return $this->render('admin/dashboard.html.twig');
    }

    public function configureDashboard(): Dashboard
    {
        return Dashboard::new()
            ->setTitle('Geslight V1.0');
    }

    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToDashboard('Dashboard', 'fa fa-home');
        //yield MenuItem::section('Stock');
        yield MenuItem::subMenu('Stock', 'fas fa-cubes')
            ->setSubItems(
                [
                    MenuItem::linkToCrud('Les types d\'opération', 'fas fa-people-carry', OperationStock::class),
                    MenuItem::linkToCrud('Lieux de stockage', 'fas fa-map-marker-alt', LieuStockage::class)
                ]
            );
        yield MenuItem::linkToCrud('Parametre','fas fa-tools', Parametre::class );

        // yield MenuItem::linkToCrud('The Label', 'fas fa-list', EntityClass::class);
    }

    public function configureUserMenu(UserInterface $user): UserMenu
    {
        return parent::configureUserMenu($user)
            ->setName($user->getNom())
            ->setGravatarEmail($user->getUserIdentifier())
            ->displayUserAvatar(true);

        // TODO: Change the autogenerated stub
    }

}
